// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// mean_sd
List mean_sd(DataFrame x, CharacterVector y, double laplace);
RcppExport SEXP _NaiveBayes_mean_sd(SEXP xSEXP, SEXP ySEXP, SEXP laplaceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DataFrame >::type x(xSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type laplace(laplaceSEXP);
    rcpp_result_gen = Rcpp::wrap(mean_sd(x, y, laplace));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_NaiveBayes_mean_sd", (DL_FUNC) &_NaiveBayes_mean_sd, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_NaiveBayes(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
